easy_admin:
  site_name: 'Pilgrims <em style="font-size: 80%;">Admin.</em>'
  list:
      max_results: 30
  design:
      brand_color: '#00134a'
      form_theme: 'vertical'
      assets:
          css:
              - '/css/admin.css'