easy_admin:
    entities:
        Location:
            class: AppBundle\Entity\Location
            label: 'Locations'
            list:
                title: '%%entity_label%%'
                sort: ['title', 'ASC']
                fields:
                    - 'title'
                    - 'region'
            form:
                fields:
                    - 'title'
                    - 'region'