easy_admin:
    entities:
        Page:
            class: AppBundle\Entity\Page
            label: 'Pages'
            list:
                title: '%%entity_label%%'
                sort: ['title', 'ASC']
                fields:
                    - 'title'
                    - 'content'
            form:
                fields:
                    - 'title'
                    - 'content'