easy_admin:
    entities:
        Region:
            class: AppBundle\Entity\Region
            label: 'Regions'
            list:
                title: '%%entity_label%%'
                sort: ['title', 'ASC']
                fields:
                    - 'title'
                    - 'country'
            form:
                fields:
                    - 'title'
                    - 'country'