<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
  public function findAll()
  {
    return $this->findBy(array(), array('title' => 'ASC'));
  }
}
