imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.site_images: /uploads/images/sites

framework:
    #esi:             ~
    translator:      { fallbacks: ["en"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Easyadmin Configuration
easy_admin:
    site_name: 'Pilgrims <em style="font-size: 80%;">Admin.</em>'
    list:
        max_results: 30
    design:
        brand_color: '#00134a'
    entities:
        Site:
            class: AppBundle\Entity\Site
            label: 'Sites'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'title'
                    - 'explanations'
                    - 'latitude'
                    - 'longitude'
                    - { property: 'imageName', type: 'image', base_path: %app.path.site_images% }
            form:
                fields:
                    - 'title'
                    - 'explanations'
                    - 'sourcesQuotation'
                    - 'latitude'
                    - 'longitude'
                    - 'history'
                    - 'archaeologicalData'
                    - 'environmentalContext'
                    - 'memorialFunctions'
                    - 'memorialFunctionsKeywords'
                    - 'liturgicalHabits'
                    - 'culticPhenomena'
                    - 'culticPhenomenaCollection'
                    - 'cultObjects'
                    - 'cultObjectsKeywords'
                    - 'additionalData'
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'sources'
                    - 'toponyms'
                    - 'historicalSources'
                    - 'literatures'
        CultObjectsKeyword:
            class: AppBundle\Entity\CultObjectsKeyword
            label: 'Cult Objects Kw'
            list:
                title: 'Cult Objects Keywords'
                fields:
                    - 'title'
        HistoricalSource:
            class: AppBundle\Entity\HistoricalSource
            label: 'Historical Sources'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'title'
                    - 'content'
        Literature:
            class: AppBundle\Entity\Literature
            label: 'Literatures'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'title'
                    - 'content'
        MemorialFunctionsKeyword:
            class: AppBundle\Entity\MemorialFunctionsKeyword
            label: 'Memorial Functions Kw'
            list:
                title: 'Memorial Functions Keywords'
                fields:
                    - 'title'
        Source:
            class: AppBundle\Entity\Source
            label: 'Sources'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'title'
                    - 'traveler'
                    - 'year'
                    - 'literatures'
        Toponym:
            class: AppBundle\Entity\Toponym
            label: 'Toponyms'
            list:
                title: '%%entity_label%%'
                fields:
                    - 'title'

# VichUploader config
vich_uploader:
    db_driver: orm
    mappings:
        site_image:
            uri_prefix: %app.path.site_images%
            upload_destination: %kernel.root_dir%/../web/uploads/images/sites
            namer: vich_uploader.namer_uniqid

# Assetic config
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~

# LiipImagineBundle
liip_imagine:
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~
    index_thumb:
      quality: 100
      filters:
        thumbnail: { size: [300, 300], mode: outbound }
