liip_imagine:
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~
    site_300:
      quality: 100
      filters:
        thumbnail: { size: [300, 300], mode: outbound }
    site_100:
      quality: 100
      filters:
        thumbnail: { size: [100, 100], mode: outbound }
    site_full:
      quality: 100