easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/"
  type:     annotation
  prefix:   /admin
app:
  resource: "@AppBundle/Controller/"
  type:     annotation
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.xml"
