# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  providers:
    shib:
      memory:
        users:
          - { name: '378257@unifr.ch', roles: 'ROLE_ADMIN' }
  firewalls:
    admin:
      pattern: ^/admin
      remote_user:
        provider: shib
      anonymous: true
    # disables authentication for assets and the profiler
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
  access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
