# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  providers:
    shib:
      memory:
        users:
          378257@unifr.ch:
            roles: 'ROLE_ADMIN'
  firewalls:
    # disables authentication for assets and the profiler
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    admin:
      pattern: ^/admin
      remote_user:
        provider: shib
        user: REMOTE_USER
      form_login:
        login_path: https://elearning.unifr.ch/Shibboleth.sso/Login
      logout:
        path: /admin/logout
        target: https://elearning.unifr.ch/Shibboleth.sso/Logout
        invalidate_session: true
