vich_uploader:
    db_driver: orm
    mappings:
        uploads:
            uri_prefix: uploads
            upload_destination: %kernel.root_dir%/../web/uploads
            namer: vich_uploader.namer_uniqid